name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildSwiftPackage:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v

  testMacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./run_tests_mac.sh

  testIOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ./run_tests_ios.sh

  buildCarthage:
    name: Build Carthage
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: carthage build --configuration Release --no-skip-current --use-xcframeworks
